
apiVersion: v1
 
kind: Service

metadata:
  name: firstservicedv
  labels :
    servicelbl: labelname
spec: 
  type: NodePort
  ports:
    - nodePort: 32000
      port: 8000
      targetPort: 8080
  selector:
          app: myapp













